---
# Whether to enable Docker TCP API
docker_remote_api_enabled: false

# Hosts to expose Docker on (Unix socket always present)
docker_remote_api_hosts:
  - "unix:///var/run/docker.sock"

# TCP port for Docker API (TLS only)
docker_remote_api_port: 2376

# Enable TLS for TCP access (must be true for prod)
docker_remote_api_tls: true
