prometheus_container_name: prometheus
prometheus_image: prom/prometheus:latest
prometheus_networks:
  - name: monitoring
prometheus_ports:
  - "9090:9090"
prometheus_config_dir: /var/lib/prometheus/config
prometheus_data_dir: /var/lib/docker/volumes/prometheus_data/_data
prometheus_targets:
  - "nginx:9113"   # Example: node_exporter/nginx exporter
