---
- name: Ensure cAdvisor container is running
  community.docker.docker_container:
    name: "{{ cadvisor_container_name }}"
    image: "{{ cadvisor_image }}"
    state: started
    restart_policy: unless-stopped

    networks: "{{ cadvisor_networks }}"
    published_ports: "{{ cadvisor_ports }}"
    volumes: "{{ cadvisor_volumes }}"
