---
mattermost_container_name: mattermost

# need to pin to a specific version
mattermost_image: mattermost/mattermost-team-edition:latest

mattermost_networks:
  - name: backend

mattermost_ports:
  - "8065:8065"

mattermost_volumes:
  - "mattermost_data:/mattermost/data"

mattermost_site_url: https://chat.example.com
mattermost_domain: chat.example.com

mattermost_env:
  MM_SERVICESETTINGS_SITEURL: "https://chat.example.com"
  MM_SQLSETTINGS_DRIVERNAME: postgres
  MM_SQLSETTINGS_DATASOURCE: "postgres://mattermost:password@postgres:5432/mattermost?sslmode=disable"
    #MM_SQLSETTINGS_DATASOURCE: "postgres://mattermost:{{ vault_mattermost_db_password }}@postgres:5432/mattermost?sslmode=disable"
