nginx_proxy_services: []
nginx_proxy_sites_path: "/var/lib/nginx/proxy_sites"

nginx_proxy_connect_timeout: 30s
nginx_proxy_send_timeout: 30s
nginx_proxy_read_timeout: 30s

nginx_proxy_client_max_body_size: 50M
