---
docker_networks:
  - name: proxy
    driver: bridge
    ipam_config:
      - subnet: 172.20.0.0/24

  - name: backend
    driver: bridge
    ipam_config:
      - subnet: 172.21.0.0/24

  - name: monitoring
    driver: bridge
    ipam_config:
      - subnet: 172.22.0.0/24


docker_volumes:
  - portainer_data
  - grafana_data
  - prometheus_data
  - mattermost_data
  - keycloak_data
  - mongodb_data
  - valkey_data
  - countly_data
  #- postgres_data # need to update

nginx_env:
  NGINX_HOST: "dev.example.com"
  NGINX_PORT: "80"

nginx_sites:
  - server_name: dev.example.com
    listen: 80
    root: /usr/share/nginx/html
    locations:
      - path: /
        content: |
          return 200 "Hello from DEV site\n";

nginx_proxy_services:
  - name: grafana       #name of docker network
    server_name: grafana.dev.example.com
    listen: 80
    upstream:
      host: grafana
      port: 3000
  - name: prometheus
    server_name: prometheus.dev.example.com
    listen: 80
    upstream:
      host: prometheus
      port: 9090

certbot_domains:
  - dev.example.com
  - grafana.dev.example.com
  - prometheus.dev.example.com

certbot_email: "ops@example.com" # replace with real later

prometheus_container_name: prometheus
prometheus_image: prom/prometheus:latest

grafana_container_name: grafana
grafana_image: grafana/grafana:latest


prometheus_targets:
  - "node_exporter:9100"
  - "cadvisor:8080"

# for concourse pipeline (docker_remote_api)
#docker_remote_api_enabled: true
#docker_remote_api_hosts:
#- "unix:///var/run/docker.sock"
#- "tcp://0.0.0.0:2376"   # Only for CI/CD internal network
#docker_remote_api_tls: false # dev/test only; production should be true
