---
- name: Ensure sites directory exists on host
  file:
    path: "{{ nginx_sites_path }}"
    state: directory
    #owner: nginx
    #group: nginx
    mode: "0755"

- name: Render nginx site configs
  template:
    src: site.conf.j2
    dest: "{{ nginx_sites_path }}/{{ item.server_name }}.conf"
    #owner: nginx
    #group: nginx
  loop: "{{ nginx_sites }}"
  notify: Reload nginx container
