---
valkey_container_name: valkey

# Pin after testing
valkey_image: valkey/valkey:8

valkey_networks:
  - name: backend

valkey_ports:
  - "6379:6379"

valkey_volumes:
  - "valkey_data:/data"

valkey_command:
  - valkey-server
  - --appendonly
  - "yes"
