---
- name: Ensure MongoDB container is running
  community.docker.docker_container:
    name:"{{ mongodb_container_name }}"
    image:"{{ mongodb_image }}"
    state: started
    restart_policy: unless-stopped

    networks:"{{ mongodb_networks }}"

    volumes:"{{ mongodb_volumes }}"
