[jumpbox]
localhost ansible_connection=local

[servers]
10.0.0.13 ansible_user=vagrant ansible_ssh_private_key_file=/home/vagrant/.ssh/id_ed25519
#10.0.0.13 ansible_user=vagrant ansible_ssh_private_key_file=/vagrant/.vagrant/machines/minion2/virtualbox/private_key
