---
- name: Ensure Node Exporter container is running
  community.docker.docker_container:
    name: "{{ node_exporter_container_name }}"
    image: "{{ node_exporter_image }}"
    state: started
    restart_policy: unless-stopped

    networks: "{{ node_exporter_networks }}"

    published_ports: "{{ node_exporter_ports }}"

    volumes: "{{ node_exporter_volumes }}"

    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"

        #cap_drop:
        #- ALL

        #read_only: true

    security_opts:
      - no-new-privileges:true

    healthcheck:
      test:
        - CMD
        - wget
        - "-q"
        - "-O"
        - "-"
        - http://localhost:9100/metrics
      interval: 30s
      timeout: 10s
      retries: 3
