---
# 1. Create service groups
- name: Create service groups
  ansible.builtin.group:
    name: "{{ item.group }}"
    state: present
  loop: "{{ users_service }}"

# 2. Create service users
- name: Create service users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    shell: /usr/sbin/nologin
    create_home: false
    system: true
    state: present
  loop: "{{ users_service }}"

# 3. Create human users
- name: Create human users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | join(',') }}"
    append: true
    shell: /bin/bash
    create_home: true
    state: present
  loop: "{{ users_human }}"

# 4. Install SSH keys for human users
- name: Install authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  loop: "{{ users_human | subelements('ssh_keys') }}"
