---
mongodb_container_name: mongodb

mongodb_image: mongo:latest #mongo:8

mongodb_networks:
  - name: backend

mongodb_ports:
  - "27017:27017"

mongodb_volumes:
  - "mongodb_data:/data/db"

mongodb_env:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password

mongodb_databases:
  - name: countly
    user: countly
    password: password
