---
# Container
keycloak_container_name: keycloak
keycloak_image: quay.io/keycloak/keycloak:26.3

# Hostname
keycloak_hostname: auth.example.com

# Network
keycloak_networks:
  - name: backend

# Ports
keycloak_ports:
  - "8080:8080"

# Volumes
keycloak_volumes:
  - "keycloak_data:/opt/keycloak/data"
  - "/opt/keycloak/themes:/opt/keycloak/themes"

# Database
keycloak_db_vendor: postgres
keycloak_db_host: postgres
keycloak_db_port: "5432"
keycloak_db_name: keycloak
keycloak_db_user: keycloak
keycloak_db_password: change-me

# Bootstrap Admin
keycloak_admin_user: admin
keycloak_admin_password: change-me

# Proxy
keycloak_proxy_headers: xforwarded

# Logging
keycloak_log_level: INFO
