---
- name: Ensure Countly container is running
  community.docker.docker_container:
    name: "{{ countly_container_name }}"
    image: "{{ countly_image }}"
    state: started
    restart_policy: unless-stopped

    networks: "{{ countly_networks }}"

    published_ports: "{{ countly_ports }}"

    volumes: "{{ countly_volumes }}"

    env: "{{ countly_env }}"

    security_opts:
      - no-new-privileges:true

  notify: Restart Countly
