---
backup_dir: /var/backups

backup_schedule: "0 2 * * *"

backup_retention_days: 30

backup_run_now: false

backup_gpg_recipient: backups@example.com

backup_s3_bucket: testing
backup_s3_prefix: production-backups

backup_volumes:
  - grafana_data
  - prometheus_data
  - mattermost_data
  - mongodb_data
  - valkey_data
  - countly_data
  - postgres_data

backup_configs:
  - /etc/nginx
  - /etc/letsencrypt

backup_postgres:
  enabled: true
  container: postgres
  user: postgres

backup_mongodb:
  enabled: true
  container: mongodb
  user: admin
  password: password
  auth_db: admin

backup_valkey:
  enabled: true
  container: valkey
