---
countly_container_name: countly

# Pin after testing
countly_image: countly/countly-server:latest

countly_networks:
  - name: backend

countly_ports:
  - "3001:80"
    #- "3001:3001"

countly_volumes:
  - "countly_data:/var/lib/countly"

countly_env:
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"

  MONGODB_DB: countly
  MONGODB_USER: countly
  MONGODB_PASSWORD: password

  REDIS_HOST: valkey
  REDIS_PORT: "6379"
