- name: Create application users
  community.docker.docker_container_exec:
    container: "{{ postgres_container_name }}"
    command: >
      psql -U {{ postgres_env.POSTGRES_USER }} -d postgres
      -c "CREATE ROLE {{ item.user }}
      WITH LOGIN PASSWORD '{{ item.password }}';"
  loop: "{{ postgres_databases }}"
  register: create_users
  failed_when:
    - create_users.rc != 0
    - "'already exists' not in (create_users.stderr | default(''))"

- name: Create application databases
  community.docker.docker_container_exec:
    container: "{{ postgres_container_name }}"
    command: >
      psql -U {{ postgres_env.POSTGRES_USER }} -d postgres
      -c "CREATE DATABASE {{ item.name }}
      OWNER {{ item.user }};"
  loop: "{{ postgres_databases }}"
  register: create_databases
  failed_when:
    - create_databases.rc != 0
    - "'already exists' not in (create_databases.stderr | default(''))"
