fail2ban_bantime: 1h
fail2ban_findtime: 10m
fail2ban_maxretry: 5

  #fail2ban_services:
  #- sshd
fail2ban_backend: systemd
fail2ban_banaction: ufw

fail2ban_sshd_enabled: true
fail2ban_sshd_port: 22

fail2ban_recidive_enabled: true

fail2ban_ignore_ips:
  - 127.0.0.1/8
  - 10.0.0.0/24
